## **LECTURA DE DATOS**

In [139]:
import pandas as pd
link='https://github.com/Tracy-12/PRACTICA-2/raw/refs/heads/main/HDI.xlsx'
HDI=pd.read_excel(link)
HDI_2=HDI.copy()
HDI_2.head()

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank
4,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN

## PASO 1

Se elimina las columnas no deseadas

In [140]:
HDI_2=HDI_2.drop(columns=['Back','Unnamed: 3','Unnamed: 5','Unnamed: 7','Unnamed: 9','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14'])
HDI_2.head()

,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita
4,Country,Value,(years),(years),(years),(2017 PPP $)

Y se cambia el nombre de las columnas

In [141]:
print(HDI_2.columns)

Index(['Table 1. Human Development Index and its components ', 'Unnamed: 2',
       'Unnamed: 4', 'Unnamed: 6', 'Unnamed: 8', 'Unnamed: 10'],
      dtype='object')

In [142]:
HDI_2= HDI_2.rename(columns={'Table 1. Human Development Index and its components ':'Country',
                             'Unnamed: 2': 'Human_Development_Index',
                             'Unnamed: 4': 'Life_expentancy_at_birth',
                             'Unnamed: 6': 'Expected_years_of_schooling',
                             'Unnamed: 8': 'Mean_years_of_schooling',
                             'Unnamed: 10': 'Gross_national_income_per_capita'})
HDI_2

,Country,Human_Development_Index,Life_expentancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita
4,Country,Value,(years),(years),(years),(2017 PPP $)
...,...,...,...,...,...,...
271,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN
272,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN
273,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN
274,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN
275,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN

### PASO 2

Se identifica las filas sobrantes

In [143]:
HDI_2.iloc[201,0]

'OTHER COUNTRIES OR TERRITORIES'

In [144]:
#Se eilimina a partir de la fila de OTHER COUNTRIEs
HDI_2 = HDI_2.drop(index=range(201, 275))
HDI_2

,Country,Human_Development_Index,Life_expentancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita
4,Country,Value,(years),(years),(years),(2017 PPP $)
...,...,...,...,...,...,...
197,Central African Republic,0.404,53.8947,8.040172,4.334,966.058611
198,Niger,0.4,61.5763,6.957112,2.116717,1239.866936
199,Chad,0.394,52.5254,8.035914,2.573774,1364.169417
200,South Sudan,0.385,54.9752,5.54251,5.72614,767.787
275,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN

In [145]:
#se busca las filas con datos perdidos
HDI_2[HDI_2.isnull().any(axis=1)]

,Country,Human_Development_Index,Life_expentancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita
5,NaN,2021,2021,2021,2021,2021
6,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN
73,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN
123,MEDIUM HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN
168,LOW HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN
275,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN

Se elimina las filas no deseadas

In [146]:
HDI_2=HDI_2.dropna(axis='rows',how='any',ignore_index=True)

In [147]:
HDI_2.head(192)

,Country,Human_Development_Index,Life_expentancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita
0,Country,Value,(years),(years),(years),(2017 PPP $)
1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981
4,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454
...,...,...,...,...,...,...
187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709
188,Central African Republic,0.404,53.8947,8.040172,4.334,966.058611
189,Niger,0.4,61.5763,6.957112,2.116717,1239.866936
190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417
191,South Sudan,0.385,54.9752,5.54251,5.72614,767.787

## PASO 3

In [149]:
HDI_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country                           192 non-null    object
 1   Human_Development_Index           192 non-null    object
 2   Life_expentancy_at_birth          192 non-null    object
 3   Expected_years_of_schooling       192 non-null    object
 4   Mean_years_of_schooling           192 non-null    object
 5   Gross_national_income_per_capita  192 non-null    object
dtypes: object(6)
memory usage: 9.1+ KB

Se verifica si hay filas con letras

In [150]:
columna=HDI_2['Human_Development_Index'].astype(str)

In [151]:
celdas_solo_letras=columna[columna.str.contains(pat=r'[a-zA-Z]',regex=True)]
celdas_solo_letras

0    Value
Name: Human_Development_Index, dtype: object

In [152]:
#se elimina la fila
HDI_2=HDI_2.drop(index=0)
HDI_2

,Country,Human_Development_Index,Life_expentancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita
1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981
4,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454
5,Australia,0.951,84.5265,21.05459,12.72682,49238.43335
...,...,...,...,...,...,...
187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709
188,Central African Republic,0.404,53.8947,8.040172,4.334,966.058611
189,Niger,0.4,61.5763,6.957112,2.116717,1239.866936
190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417
191,South Sudan,0.385,54.9752,5.54251,5.72614,767.787

## PASO 4

In [154]:
HDI_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 1 to 191
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country                           191 non-null    object
 1   Human_Development_Index           191 non-null    object
 2   Life_expentancy_at_birth          191 non-null    object
 3   Expected_years_of_schooling       191 non-null    object
 4   Mean_years_of_schooling           191 non-null    object
 5   Gross_national_income_per_capita  191 non-null    object
dtypes: object(6)
memory usage: 9.1+ KB

Como los datos numericos siguen como object , se convierte los datos

In [155]:
#PRIMERA COLUMNA
HDI_2['Human_Development_Index']=pd.to_numeric(HDI_2['Human_Development_Index'])
HDI_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 1 to 191
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country                           191 non-null    object
 1   Human_Development_Index           191 non-null    float64
 2   Life_expentancy_at_birth          191 non-null    object
 3   Expected_years_of_schooling       191 non-null    object
 4   Mean_years_of_schooling           191 non-null    object
 5   Gross_national_income_per_capita  191 non-null    object
dtypes: float64(1), object(5)
memory usage: 9.1+ KB

In [156]:
#SEGUNDA COLUMNA
HDI_2['Life_expentancy_at_birth']=pd.to_numeric(HDI_2['Life_expentancy_at_birth'])
HDI_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 1 to 191
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country                           191 non-null    object
 1   Human_Development_Index           191 non-null    float64
 2   Life_expentancy_at_birth          191 non-null    float64
 3   Expected_years_of_schooling       191 non-null    object
 4   Mean_years_of_schooling           191 non-null    object
 5   Gross_national_income_per_capita  191 non-null    object
dtypes: float64(2), object(4)
memory usage: 9.1+ KB

In [157]:
#TERCERA COLUMNA
HDI_2['Expected_years_of_schooling']=pd.to_numeric(HDI_2['Expected_years_of_schooling'])
HDI_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 1 to 191
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country                           191 non-null    object
 1   Human_Development_Index           191 non-null    float64
 2   Life_expentancy_at_birth          191 non-null    float64
 3   Expected_years_of_schooling       191 non-null    float64
 4   Mean_years_of_schooling           191 non-null    object
 5   Gross_national_income_per_capita  191 non-null    object
dtypes: float64(3), object(3)
memory usage: 9.1+ KB

In [158]:
#CUARTA COLUMNA
HDI_2['Mean_years_of_schooling']=pd.to_numeric(HDI_2['Mean_years_of_schooling'])
HDI_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 1 to 191
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country                           191 non-null    object
 1   Human_Development_Index           191 non-null    float64
 2   Life_expentancy_at_birth          191 non-null    float64
 3   Expected_years_of_schooling       191 non-null    float64
 4   Mean_years_of_schooling           191 non-null    float64
 5   Gross_national_income_per_capita  191 non-null    object
dtypes: float64(4), object(2)
memory usage: 9.1+ KB

In [159]:
#QUINTA COLUMNA
HDI_2['Gross_national_income_per_capita']=pd.to_numeric(HDI_2['Gross_national_income_per_capita'])
HDI_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 1 to 191
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country                           191 non-null    object
 1   Human_Development_Index           191 non-null    float64
 2   Life_expentancy_at_birth          191 non-null    float64
 3   Expected_years_of_schooling       191 non-null    float64
 4   Mean_years_of_schooling           191 non-null    float64
 5   Gross_national_income_per_capita  191 non-null    float64
dtypes: float64(5), object(1)
memory usage: 9.1+ KB

## PASO 5

Por ultimo se añade la columna con la categorias

In [160]:
HDI_2['Category']=pd.cut(HDI_2['Human_Development_Index'],
                         bins=[0,0.549,0.699,0.796,1],
                         labels=['LOW HUMAN DEVELOPMENT','MEDIUM HUMAN DEVELOPMENT','HIGH HUMAN DEVELOPMENT','VERY HIGH HUMAN DEVELOPMENT'],
                           ordered=True)
HDI_2

,Country,Human_Development_Index,Life_expentancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita,Category
1,Switzerland,0.962,83.9872,16.500299,13.859660,66933.004540,VERY HIGH HUMAN DEVELOPMENT
2,Norway,0.961,83.2339,18.185200,13.003630,64660.106220,VERY HIGH HUMAN DEVELOPMENT
3,Iceland,0.959,82.6782,19.163059,13.767170,55782.049810,VERY HIGH HUMAN DEVELOPMENT
4,"Hong Kong, China (SAR)",0.952,85.4734,17.278170,12.226210,62606.845400,VERY HIGH HUMAN DEVELOPMENT
5,Australia,0.951,84.5265,21.054590,12.726820,49238.433350,VERY HIGH HUMAN DEVELOPMENT
...,...,...,...,...,...,...,...
187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,LOW HUMAN DEVELOPMENT
188,Central African Republic,0.404,53.8947,8.040172,4.334000,966.058611,LOW HUMAN DEVELOPMENT
189,Niger,0.400,61.5763,6.957112,2.116717,1239.866936,LOW HUMAN DEVELOPMENT
190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,LOW HUMAN DEVELOPMENT
191,South Sudan,0.385,54.9752,5.542510,5.726140,767.787000,LOW HUMAN DEVELOPMENT

In [162]:
HDI_2['Human_Development_Index'] = HDI_2['Human_Development_Index'].apply(lambda x: round(x, 3))
HDI_2['Life_expentancy_at_birth'] = HDI_2['Life_expentancy_at_birth'].apply(lambda x: round(x, 1))
HDI_2['Expected_years_of_schooling'] = HDI_2['Expected_years_of_schooling'].apply(lambda x: round(x, 1))
HDI_2['Mean_years_of_schooling'] = HDI_2['Mean_years_of_schooling'].apply(lambda x: round(x, 1))
HDI_2['Gross_national_income_per_capita'] = HDI_2['Gross_national_income_per_capita'].apply(lambda x: round(x, 0))
HDI_2

,Country,Human_Development_Index,Life_expentancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita,Category
1,Switzerland,0.962,84.0,16.5,13.9,66933.0,VERY HIGH HUMAN DEVELOPMENT
2,Norway,0.961,83.2,18.2,13.0,64660.0,VERY HIGH HUMAN DEVELOPMENT
3,Iceland,0.959,82.7,19.2,13.8,55782.0,VERY HIGH HUMAN DEVELOPMENT
4,"Hong Kong, China (SAR)",0.952,85.5,17.3,12.2,62607.0,VERY HIGH HUMAN DEVELOPMENT
5,Australia,0.951,84.5,21.1,12.7,49238.0,VERY HIGH HUMAN DEVELOPMENT
...,...,...,...,...,...,...,...
187,Burundi,0.426,61.7,10.7,3.1,732.0,LOW HUMAN DEVELOPMENT
188,Central African Republic,0.404,53.9,8.0,4.3,966.0,LOW HUMAN DEVELOPMENT
189,Niger,0.400,61.6,7.0,2.1,1240.0,LOW HUMAN DEVELOPMENT
190,Chad,0.394,52.5,8.0,2.6,1364.0,LOW HUMAN DEVELOPMENT
191,South Sudan,0.385,55.0,5.5,5.7,768.0,LOW HUMAN DEVELOPMENT

In [163]:
HDI_2.to_excel('HDI_2.xlsx')